export const franchiseDetails = [
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "8000-10000",
    investments: "INR 5 Cr to 10 Cr",
    outlets: "100 to 200 Outlets",
    button: "Know More",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "7000-9000",
    investments: "INR 3 Cr to 5 Cr",
    outlets: "100 to 150 Outlets",
    button: "Know More",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "6000-10000",
    investments: "INR 5 Cr to 8 Cr",
    outlets: "150 to 200 Outlets",
    button: "Know More",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "5000-8000",
    investments: "INR 5 Cr to 8 Cr",
    outlets: "100 to 200 Outlets",
    button: "Know More",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
  {
    image: "/Multi Bee final.jpg",
    title: "Multi Bee",
    area: "",
    investments: "",
    outlets: "",
    button: "",
  },
];
