export const franchiseDetails = [
  {
    image: '/Croma.jpg',
    title: 'Croma',
    area: '8000-10000',
    investments: 'INR 5 Cr to 10 Cr',
    outlets: '100 to 200 Outlets',
    button: 'Know More',
  },
  {
    image: '/Behrouz.jpg',
    title: 'Behrouz Biryani',
    area: '7000-9000',
    investments: 'INR 3 Cr to 5 Cr',
    outlets: '100 to 150 Outlets',
    button: 'Know More',
  },
  {
    image: '/CCD.png',
    title: 'CCD',
    area: '6000-10000',
    investments: 'INR 5 Cr to 8 Cr',
    outlets: '150 to 200 Outlets',
    button: 'Know More',
  },
  {
    image: '/Dominos.jpg',
    title: 'Dominos',
    area: '5000-8000',
    investments: 'INR 5 Cr to 8 Cr',
    outlets: '100 to 200 Outlets',
    button: 'Know More',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
  {
    image: '',
    title: '',
    area: '',
    investments: '',
    outlets: '',
    button: '',
  },
]